[directory]
fish_style_pwd_dir_length = 1

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"

[time]
disabled = false
use_12hr = true
format = '[$time]($style) '
time_format = "%I:%M"
style = "246"

[nix_shell]
symbol = ' '
format = 'via [$symbol$state]($style) '

