#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"


#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down


#boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
  picom &> /dev/null &
elif [ -x "$(command -v compton)" ]; then
  compton &> /dev/null &
fi


#set the theme.ron config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"


#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/nix-black-4k.png
fi


#start the bar
thledbar &> /dev/null &

