theme = "gruvbox"

[editor]
auto-format = true
auto-pairs = true
auto-save = false
completion-trigger-len = 3
line-number = "relative"
middle-click-paste = false
mouse = false
rulers = [120]
text-width = 120
true-color = true

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator", "file-type", "total-line-numbers", "file-encoding"]
center = ["diagnostics", "workspace-diagnostics"]
right = ["selections", "primary-selection-length", "position", "position-percentage"]

[editor.file-picker]
hidden = false

[editor.whitespace.render]
nbsp = "all"
newline = "none"
space = "none"
tab = "all"

[editor.whitespace.characters]
nbsp = "⍽"
newline = "⏎"
space = "·"
tab = "→"
tabpad = " "

[editor.indent-guides]
character = "▏"
render = true
skip-levels = 0

[editor.soft-wrap]
enable = true
max-indent-retain = 40
max-wrap = 20
wrap-at-text-width = false
wrap-indicator = "↪"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

down = "move_line_down"
up = "move_line_up"

A-F = "extend_prev_char"
A-f = "find_prev_char"
A-T = "extend_till_prev_char"
A-t = "till_prev_char"
B = "extend_prev_word_start"
E = "extend_next_word_end"
F = "extend_next_char"
T = "extend_till_char"
W = "extend_next_word_start"
X = "extend_line_above"

[keys.normal.g]
h = ["collapse_selection", "extend_to_line_start"]
H = ["extend_to_line_start"]
l = ["collapse_selection", "extend_to_line_end"]
L = ["extend_to_line_end"]
s = ["collapse_selection", "extend_to_first_nonwhitespace"]
S = ["extend_to_first_nonwhitespace"]

[keys.normal.m]
m = ["collapse_selection", "select_mode", "match_brackets", "exit_select_mode"]

[keys.normal.space]
space = "flip_selections"