theme = "catppuccin_mocha"

[editor]
mouse = false
middle-click-paste = false
line-number = "relative"
auto-format = true
auto-save = false
completion-trigger-len = 3
true-color = true
rulers = [120]
text-width = 120
auto-pairs = false

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "none"
nbsp = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = " "

[editor.indent-guides]
render = true
character = "│"
skip-levels = 0

[editor.soft-wrap]
enable = true
max-wrap = 20
max-indent-retain = 40
wrap-indicator = "↪"
wrap-at-text-width = false

[keys.normal]
esc = "collapse_selection"

[keys.normal.g]
l = ["collapse_selection", "extend_to_line_end"]
h = ["collapse_selection", "extend_to_line_start"]
s = ["collapse_selection", "extend_to_first_nonwhitespace"]

[keys.normal.m]
m = ["collapse_selection", "select_mode", "match_brackets", "exit_select_mode"]